spring:
  logstash:
    url:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    serialization:
      write_dates_as_timestamps: false
  sleuth:
    supports-join: false

logging:
  level:
    root: info
    org:
      springframework:
        web: info

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
